name: Bisha's website 
desciption: Caran d'Arche is a pencil who's looking for an opportunity 
twitter_username: Bisha
github_username: Bishathomas
author: Bishathomas@gmail.com

markdown: kramdown

remote_theme: just-the-doc/just-the-doc
